"""init

Revision ID: fb63d502c17f
Revises: 
Create Date: 2026-05-09 13:46:37.432735
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fb63d502c17f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=25), nullable=False),
    sa.Column('source_lang', sa.String(length=5), nullable=False),
    sa.Column('target_lang', sa.String(length=5), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'source_lang', 'target_lang', 'source_text', name='uq_context_cache')
    )
    op.create_table('definition_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=25), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'lang', 'word', name='uq_definition_cache')
    )
    op.create_table('lexical_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=25), nullable=False),
    sa.Column('source_lang', sa.String(length=5), nullable=False),
    sa.Column('target_lang', sa.String(length=5), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'source_lang', 'target_lang', 'word', name='uq_lexical_cache')
    )
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=25), nullable=False),
    sa.Column('source_lang', sa.String(length=5), nullable=False),
    sa.Column('target_lang', sa.String(length=5), nullable=False),
    sa.Column('detected_lang', sa.String(length=5), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'source_lang', 'target_lang', 'source_text', name='uq_translation_cache')
    )
    op.create_table('tts_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=25), nullable=False),
    sa.Column('voice', sa.String(length=100), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speed_ratio', sa.Integer(), server_default='100', nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('needs_encode', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'voice', 'lang', 'text', 'speed_ratio', name='uq_tts_cache')
    )
    op.create_index('ix_tts_cache_needs_encode', 'tts_cache', ['id'], unique=False, postgresql_where=sa.text('needs_encode IS TRUE'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_language_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(length=5), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_prefs_user_id'), 'user_language_prefs', ['user_id'], unique=False)
    op.create_table('user_provider_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=25), nullable=False),
    sa.Column('provider_code', sa.String(length=25), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_provider_prefs_user_id'), 'user_provider_prefs', ['user_id'], unique=False)
    op.create_table('user_tts_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('voice', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tts_prefs_user_id'), 'user_tts_prefs', ['user_id'], unique=False)
    op.create_table('word_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_word_groups_user_name')
    )
    op.create_index(op.f('ix_word_groups_user_id'), 'word_groups', ['user_id'], unique=False)
    op.create_table('wordbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=25), nullable=True),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=15), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['word_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordbook_entries_group_id'), 'wordbook_entries', ['group_id'], unique=False)
    op.create_index(op.f('ix_wordbook_entries_user_id'), 'wordbook_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordbook_entries_user_id'), table_name='wordbook_entries')
    op.drop_index(op.f('ix_wordbook_entries_group_id'), table_name='wordbook_entries')
    op.drop_table('wordbook_entries')
    op.drop_index(op.f('ix_word_groups_user_id'), table_name='word_groups')
    op.drop_table('word_groups')
    op.drop_index(op.f('ix_user_tts_prefs_user_id'), table_name='user_tts_prefs')
    op.drop_table('user_tts_prefs')
    op.drop_index(op.f('ix_user_provider_prefs_user_id'), table_name='user_provider_prefs')
    op.drop_table('user_provider_prefs')
    op.drop_index(op.f('ix_user_language_prefs_user_id'), table_name='user_language_prefs')
    op.drop_table('user_language_prefs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tts_cache_needs_encode', table_name='tts_cache', postgresql_where=sa.text('needs_encode IS TRUE'))
    op.drop_table('tts_cache')
    op.drop_table('translation_cache')
    op.drop_table('lexical_cache')
    op.drop_table('definition_cache')
    op.drop_table('context_cache')
    # ### end Alembic commands ###
